# Build and run:
#   docker build --build-arg DEV_HOME=$HOME --build-arg DEV_USER_NAME=$USER --build-arg=DEV_USER_PWD=1234 --build-arg DEV_UID=$(id -u) --build-arg DOMAINUSERS_GID=$(id -g) --rm -t dotfiles:test -f Dockerfile.test docker
#   docker build --build-arg DEV_HOME=$HOME --build-arg DEV_USER_NAME=$USER --build-arg=DEV_USER_PWD=1234 --build-arg DEV_UID=$(id -u) --build-arg DOMAINUSERS_GID=$(id -g) --rm -t dotfiles:latest -f Dockerfile docker
#
# ssh credentials (test user):
#   ssh -t -p 3000 $USER@localhost "bash --login"
#   ssh -t -p 3000 $USER@localhost "cd ~/path/to/project/ ; bash --login"

FROM ubuntu:22.04

# Update package lists and install SSH server
RUN apt-get update && apt-get upgrade -y                    \
    && apt-get install -y sudo                              \
    && apt-get clean

ARG DEV_USER_NAME=dev
ARG DEV_USER_PWD=1234
ARG DEV_UID=1003
ARG DOMAINUSERS_GID=1003
ARG DEV_HOME=/home/${DEV_USER_NAME}

ENV ROOT_PWD=1234

RUN if ! getent group ${DOMAINUSERS_GID}; then \
        groupadd -g ${DOMAINUSERS_GID} domainusers; \
    else \
        EXISTING_GROUP=$(getent group ${DOMAINUSERS_GID} | cut -d: -f1); \
        echo "Group with GID ${DOMAINUSERS_GID} already exists as $EXISTING_GROUP"; \
    fi \
    && useradd -m -d ${DEV_HOME} ${DEV_USER_NAME} -u ${DEV_UID} -g ${EXISTING_GROUP:-domainusers} \
    && usermod -a -G sudo ${DEV_USER_NAME} \
    && yes ${DEV_USER_PWD} | passwd ${DEV_USER_NAME} \
    && echo 'root:'${ROOT_PWD} | chpasswd; \
    # allow sudo for group 'sudo' (no password in containers)
    printf '%%sudo ALL=(ALL) NOPASSWD:ALL\n' > /etc/sudoers.d/99-sudo; \
    chmod 0440 /etc/sudoers.d/99-sudo

RUN usermod -s /bin/bash ${DEV_USER_NAME}

ENV PATH="${ASDF_DATA_DIR:-$DEV_HOME/.asdf}/shims:${DEV_HOME}/.local/bin:${PATH}"

USER ${DEV_USER_NAME}
RUN mkdir -p ${DEV_HOME}/.local/bin

