#!/usr/bin/env bash

if [ -d "${HOME}/.zsh_completions.d" ]; then
  setopt nullglob
  for completion in "${HOME}"/.zsh_completions.d/*; do
    if [ -f "$completion" ]; then
      . "$completion"
    fi
  done
  unsetopt nullglob
  unset completion
fi
