#!/usr/bin/env bash

if [ -d "${HOME}/.zsh_completion.d" ]; then
  for completion in "${HOME}"/.zsh_completion.d/*; do
    if [ -f "$completion" ] && [ -x "$completion" ]; then
      #echo "Reading completion file: $completion"
      . "$completion"
    elif [ -f "$completion" ]; then
      . "$completion"
    fi
  done
  unset completion
fi
